import fs from 'fs';
import path from 'path';

export interface FlowResult {
  flow: string;
  status: 'pass' | 'fail' | 'skip';
  error?: string;
  durationMs?: number;
}

export interface QAReport {
  runId: string;
  timestamp: string;
  totalFlows: number;
  passed: number;
  failed: number;
  skipped: number;
  flowResults: FlowResult[];
  aiAnalysis: string;
  fixStubs: string;
  uxFeedback: string;
  selfImprovements: string;
}

export function buildReport(data: QAReport): string {
  const failedFlows = data.flowResults.filter(r => r.status === 'fail');
  const passedFlows = data.flowResults.filter(r => r.status === 'pass');
  const statusEmoji = data.failed === 0 ? '✅' : data.failed <= 3 ? '⚠️' : '🔴';

  return `# ${statusEmoji} Cortex Auto-QA Report
**Run ID**: \`${data.runId}\`  
**Timestamp**: ${data.timestamp}  
**Status**: ${data.failed === 0 ? 'ALL PASSING' : `${data.failed} FAILURES DETECTED`}

---

## 📊 Summary
| Metric | Count |
|--------|-------|
| Total Flows | ${data.totalFlows} |
| ✅ Passed | ${data.passed} |
| ❌ Failed | ${data.failed} |
| ⏭ Skipped | ${data.skipped} |

---

## ✅ Passing Flows
${passedFlows.map(f => `- \`${f.flow}\` ${f.durationMs ? `(${f.durationMs}ms)` : ''}`).join('\n') || '_None_'}

---

## ❌ Failed Flows
${failedFlows.length === 0 ? '_No failures_ 🎉' : failedFlows.map(f => `
### ❌ ${f.flow}
\`\`\`
${f.error ?? 'Unknown error'}
\`\`\`
`).join('\n')}

---

## 🔍 AI QA Analysis
${data.aiAnalysis}

---

## 🩹 Suggested Fix Stubs
${data.fixStubs}

---

## 👤 End-User UX Feedback
${data.uxFeedback}

---

## 🔄 Self-Improvement Suggestions
${data.selfImprovements}

---
*Generated by Cortex Auto-QA Agent — powered by qwen3:14b + qwen3-coder:30b via Ollama*
`;
}

export function saveReport(report: QAReport): string {
  const dir = path.resolve(__dirname, 'reports');
  fs.mkdirSync(dir, { recursive: true });

  const filename = `qa-${report.runId}.md`;
  const filepath = path.join(dir, filename);
  const content = buildReport(report);

  fs.writeFileSync(filepath, content, 'utf-8');
  fs.writeFileSync(path.join(dir, 'latest.md'), content, 'utf-8');

  console.log(`\n📄 Report saved: ${filepath}`);
  return filepath;
}

export function printSummary(report: QAReport): void {
  const bar = (passed: number, total: number) => {
    const pct = Math.round((passed / Math.max(total, 1)) * 20);
    return '█'.repeat(pct) + '░'.repeat(20 - pct);
  };

  console.log('\n' + '═'.repeat(60));
  console.log('  🧠 CORTEX AUTO-QA SUMMARY');
  console.log('═'.repeat(60));
  console.log(`  Run:    ${report.runId}`);
  console.log(`  Time:   ${report.timestamp}`);
  console.log(`  [${bar(report.passed, report.totalFlows)}] ${report.passed}/${report.totalFlows} passed`);
  if (report.failed > 0) {
    console.log(`\n  ❌ FAILURES:`);
    report.flowResults
      .filter(r => r.status === 'fail')
      .forEach(f => console.log(`     • ${f.flow}: ${f.error?.slice(0, 80) ?? 'unknown'}`));
  }
  console.log('═'.repeat(60) + '\n');
}

export function generateRunId(): string {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
}
